# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the requirements file to leverage Docker cache
COPY ai-backend/requirements.txt ./

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Bundle app source
COPY ai-backend/ .

# Expose the port the app runs on
EXPOSE 5001

# Define the command to run your app
CMD ["python", "ai_dart_detection.py"]
